"""initial schema

Revision ID: 29cb53496a3f
Revises: 
Create Date: 2026-08-14 15:50:09.317444

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29cb53496a3f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_twitch_id'), 'channels', ['twitch_id'], unique=True)
    op.create_index(op.f('ix_channels_username'), 'channels', ['username'], unique=True)
    op.create_table('streamers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streamers_twitch_id'), 'streamers', ['twitch_id'], unique=True)
    op.create_table('vods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_vod_id', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('stream_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('chat_ingested', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vods_twitch_vod_id'), 'vods', ['twitch_vod_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('vod_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vod_offset_secs', sa.Integer(), nullable=True),
    sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emote_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['vod_id'], ['vods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_channel_user', 'chat_messages', ['channel_id', 'username'], unique=False)
    op.create_index('idx_chat_sent_at', 'chat_messages', ['sent_at'], unique=False)
    op.create_index('idx_chat_vod', 'chat_messages', ['vod_id', 'vod_offset_secs'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_vod', table_name='chat_messages')
    op.drop_index('idx_chat_sent_at', table_name='chat_messages')
    op.drop_index('idx_chat_channel_user', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_vods_twitch_vod_id'), table_name='vods')
    op.drop_table('vods')
    op.drop_index(op.f('ix_streamers_twitch_id'), table_name='streamers')
    op.drop_table('streamers')
    op.drop_index(op.f('ix_channels_username'), table_name='channels')
    op.drop_index(op.f('ix_channels_twitch_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
