"""add vod chunks_ingested flag

Revision ID: c8ea5ea6d1c7
Revises: 29cb53496a3f
Create Date: 2026-08-16 00:11:39.727606

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8ea5ea6d1c7'
down_revision: str | None = '29cb53496a3f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'vods',
        sa.Column('chunks_ingested', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('vods', 'chunks_ingested', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vods', 'chunks_ingested')
    # ### end Alembic commands ###
